### ISSUE TITLE
Allow empty values in K8S resource dictionaries

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#5836]
# Prerequisites

- [ * ] I have verified the problem exists in the latest version
- [ * ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ * ] I have written a descriptive issue title
- [ * ] I have linked the original source of this report
- [ * ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

Octopus currently removes entries from Kubernetes resource dictionaries where the value or key is empty. Empty values are valid though. See https://github.com/istio/istio/issues/9504 for an example - the empty annotation `readiness.status.sidecar.istio.io/applicationPorts` is used to work around an issue in Istio.

This is also true of labels, configmap and secret data. For example, the following is a valid ConfigMap resource:

```
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: example-configmap
  labels:
    key0: ""
    key1: hi
  annotations:
    key0: ""
    key1: hi
data:
  database: ""
  database_uri: "value"
```

## What I expected to happen

Octopus should allow dictionary entries with empty keys.

## Steps to reproduce

1. Create a new deployment with the `Deploy Kubernetes containers` step
2. Add a `Pod Annotation` with a valid key and an empty value
3. Deploy the step
4. The annotation was not added to the pod

## Affected versions

All versions up to 2019.8.3

## Workarounds

Deploying the raw yaml of the Kubernetes resources can be used to add dictionaries with empty values.
