### ISSUE TITLE
Linux Docker images lack a Bash option for script step when run on server

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6228]
# Prerequisites

- [ * ] I have verified the problem exists in the latest version
- [ * ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ * ] I have written a descriptive issue title
- [  ] I have linked the original source of this report
- [ * ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

The Linux Docker image does not expose a Bash option for the `Run a script` step when `Run on the Octopus server` option is selected.

The image also lacks Powershell, so without a worker the step can not be used.

## What I expected to happen

`Run a script` step should be usable out of the box for a Linux Docker image.

## Steps to reproduce

1. Start the Octopus Linux Docker image
2. Create a `Run a script` step with `Run on the Octopus server` option selected
3. Note that there is no Bash option

### Screen capture

![image](https://user-images.githubusercontent.com/160104/75947952-cd216780-5eed-11ea-82f5-6b2a13a57b1b.png)

## Affected versions

All released versions.

## Workarounds

You can add Powershell to the base image and Octopus will run `pwsh` in Linux.

**Comment by mcasperson** [comment]
This `docker-compose.yml` file will create a test environment:

```
version: '3'
services:
  octopus:
    ports:
      - "8080:8080"
      - "11943:10943"
    environment:
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: octopusguides@gmail.com
      ADMIN_PASSWORD: Password01!
      ACCEPT_EULA: Y
      DB_CONNECTION_STRING: Server=host.docker.internal,7777;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      CONNSTRING: Server=host.docker.internal,7777;Database=Octopus;User Id=SA;Password=Password01!;ConnectRetryCount=6
      MASTER_KEY: 6EdU6IWsCtMEwk0kPKflQQ==
    image: octopusdeploy/octopusdeploy-prerelease:2020.1.1-ci0205.linux
    labels:
      autoheal: true
    depends_on:
      - mssql
  mssql:
    ports:
      - "7777:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password01!
      MSSQL_PID: Express 
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
```
