### ISSUE TITLE
Kubernetes Ingress does not import full certificate chain

### ISSUE THREAD

**Issue by mcasperson** [OctopusDeploy/Issues#6506]
**_Are you a customer of Octopus Deploy? Don't raise the issue here. Please contact [our support team](https://octopus.com/support) so we can triage your issue, making sure it's handled appropriately._**

# Prerequisites

- [ * ] I have verified the problem exists in the latest version
- [ * ] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [ * ] I have written a descriptive issue title
- [ * ] I have linked the original source of this report
- [ * ] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

When importing a certificate into Kubernetes via the Ingress step, the certificate chain is ignored.

## What I expected to happen

The K8s secret should contain the certificate and chain.

## Steps to reproduce

1. Add a `Deploy Kubernetes Ingress resource` step
2. Click the `ADD TLS CERTIFICATE` button
3. Select an `Octopus Certificate` that has a certificate chain
4. When the K8s secret is created with the certificate contents, the certificate chain is not present

## Affected versions

All versions to 2020.4.0

## Workarounds

K8s certificates can be manually created with kubectl:

```
Set-Content -Path secret.yaml -Value @"
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: mycert
data:
  tls.crt: $([Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("#{MyCertificateVariable.CertificatePem}#{MyCertificateVariable.ChainPem}")))
  tls.key: $([Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("#{MyCertificateVariable.PrivateKeyPem}")))
"@

kubectl apply -f secret.yaml
```

## Links

Internal line: https://secure.helpscout.net/conversation/1241058485/68331/
