### ISSUE TITLE
Kubernetes steps do not transform computed variables in files

### ISSUE THREAD

**Issue by andrewabest** [OctopusDeploy/Issues#6570]
# Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

If a computed or environment variable is referenced in a field in any of:

- Kubernetes Deploy container step
- Kubernetes Deploy ingress step
- Kubernetes Deploy raw yaml step
- Kubernetes Deploy service step

Such as `#{Octopus.Actions.KubernetesContainers.ComputedSecretName}` or `#{env:COMPUTERNAME}`, it will fail to resolve this variable at deployment time.

An error similar to:

> Error | * spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name: Invalid value: "#{Octopus.Action.KubernetesContainers.ComputedSecretName}"

Will be displayed in the deployment log.

## What I expected to happen

Variables should be replaced in the deployed yaml, including `Computed` and Environment variables.

## Steps to reproduce

This reproduction requires that you have a healthy kubernetes cluster deployment target.

1. Create an empty deployment process
2. Go to "Process" and "Add Step"
3. Select "Kubernetes" and then the "Deploy raw kubernetes yaml"
4. Click "Add Source Code" and add the following YAML to the step

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{env:COMPUTERNAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      Octopus.Kubernetes.DeploymentName: #{env:COMPUTERNAME}
  template:
    metadata:
      labels:
        Octopus.Kubernetes.DeploymentName: "abc123"
    spec:
      containers:
      - name: test-#{env:COMPUTERNAME}
        image: index.docker.io/nginx
        securityContext: {}
      affinity: {}
      dnsConfig: {}
  strategy:
    type: RollingUpdate
```

5. Ensure the step targets your kubernetes cluster role
6. Create and deploy a release to an environment your cluster is available within

### Screen capture

![image](https://user-images.githubusercontent.com/2706018/92683568-62585980-f372-11ea-8dc4-548c260f1256.png)

## Affected versions

**Octopus Server: 2020.4-rc5**

## Workarounds

None.

## Links

[Internal Link](https://secure.helpscout.net/conversation/1277067058/70266?folderId=325273)
