### ISSUE TITLE
Providing an admin password and API key to the Octopus Server docker container doesn't work as described in the docs

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusDeploy/Issues#6629]
#Prerequisites

- [x] I have verified the problem exists in the latest version
- [x] I have searched [open](https://github.com/OctopusDeploy/Issues/issues) and [closed](https://github.com/OctopusDeploy/Issues/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) issues to make sure it isn't already reported
- [x] I have written a descriptive issue title
- [x] I have linked the original source of this report
- [x] I have tagged the issue appropriately (area/*, kind/bug, tag/regression?)

# The bug

You cannot login with the admin account if you set a password and an API key. This is not in line with the comment from our example docker file.

> The API Key to set for the administrator. If this is set and no password is provided then a service account user will be created. If this is set and a password is also set then a standard user will be created.

## What I expected to happen

To be able to login with an admin account when password and API key are provided.

## Steps to reproduce

1. Use this docker-compose.yml and `docker-compose up`

```yml
version: "3"
services:
  db1:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "N0tS3cr3t!"
      ACCEPT_EULA: "Y"
      # Prevent SQL Server from consuming the defult of 80% physical memory.
      MSSQL_MEMORY_LIMIT_MB: 2048
    ports:
      - 1401:1433
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "N0tS3cr3t!",
          "-Q",
          "select 1",
        ]
      interval: 10s
      retries: 10
  octopus-server:
    image: octopusdeploy/octopusdeploy:2020.4
    privileged: true
    environment:
      ACCEPT_EULA: "Y"
      OCTOPUS_SERVER_NODE_NAME: "octopus-local-2"
      DB_CONNECTION_STRING: "Server=db1,1433;Database=OctopusDeploy-local;User=sa;Password=N0tS3cr3t!"
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "Passw0rd123"
      ADMIN_EMAIL: "tam@octopus.com"
      ADMIN_API_KEY: "API-VRCTL0YFVVEEJLRBRPWK"
      OCTOPUS_SERVER_BASE64_LICENSE: ""
      MASTER_KEY: ""
    ports:
      - 8080:8080
      - 10943:10943
    depends_on:
      - db1
```

2. Open localhost:8080
3. Try to login with `admin` and `Passw0rd123`.
4. See "invalid username or password" error.

## Affected versions

Tested on

**Octopus Server:** 2020.4 

## Workarounds

Remove the API key from the docker-compose file.

## Links

https://stackoverflow.com/questions/64313858/cannot-sign-in-to-octopus-deploy-after-docker-installation/64321621?noredirect=1#comment113755848_64321621
