### ISSUE TITLE
"Deploy Kubernetes Containers" process page breaks if invalid YAML is entered

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#7260]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low, but with quality perception impact for customers

### Version

2021.3.6515. Not present in 2021.2.7930

### Latest Version

I could reproduce the problem in the latest build

### What happened?

If invalid YAML is entered into the "Deployment > Edit YAML" section of the Deploy Kubernetes Containers step, an unhandled Javascript exception causes a large React stacktrace to be displayed in place of the process editor. Some navigation elements are also broken, so getting back to edit your process is difficult.

### Reproduction

1. In Library > External Feeds, add a new Feed. Set the Feed Type to "Docker Container Registry", the Name to whatever you want, and keep the default feed URL. Save the feed.
2. Add a "Deploy Kubernetes Containers" step to a deployment process
3. Click the "Edit YAML" button under the Deployment > Edit YAML section of the process editor
4. Make a change to make the YAML invalid, eg change the "kind" property to something unsupported:
```YAML
# This YAML exposes the fields defined in the UI. It can be edited directly or have new YAML pasted in.
# Not all available Kubernetes properties are recognized by the form exposed in the UI, and unrecognized properties are ignored during import.
# If the required properties are not supported by this step, the 'Deploy raw Kubernetes YAML' step can be used to deploy YAML directly to Kubernetes, and supports all properties.
apiVersion: apps/v1
kind: not-a-real-kind-of-kubernetes-yaml
metadata:
  name: octopus-deployment
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExport
    spec: {}
```
5. Click the "Done" button

**Expected**: 
- A graceful validation message is shown
- The user can fix their YAML and continue editing the Step

**Actual**
- A large React error completely replaces the process editor
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/730704/145928897-6292302a-5eef-4fae-97a2-1856a2819052.png">

- Some of the left-menu navigation elements are broken (eg Overview, Process and Channels), so you can't easily navigate away from the error and back into the process editor
- Any progress on the Step definition is lost

### Error and Stacktrace

```shell
An unexpected error occurred in Octopus v2021.3.9694: "undefined: undefined"
in KubernetesDeployContainersActionEditInternal
in edit
in Unknown
in Unknown
in div
in div
in div
in TransitionAnimation
in div
in div
in PaperLayout
in ve
in ExpandableContainer
in ProcessActionDetailsInternal
in ProcessActionDetails
in Unknown
in Page
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in Unknown
in RenderWithPage
in EnhancedProcessActionDetailsPage
in div
in t
in ForwardRef
in div
in div
in ProcessSidebarLayout
in div
in TransitionAnimation
in div
in div
in PaperLayout
in div
in KeyboardHandler
in div
in FormComponent
in Unknown
in FormPaperLayout
in withRouter(FormPaperLayout)
in ProjectContextFormPaperLayout
in DeploymentsProcessEditorFormPaperLayout
in ProcessContextFormPaperLayout
in withRouter(ProcessContextFormPaperLayout)
in ProcessWarningActions
in ProcessErrorActions
in ProcessStepsLayout
in EnhancedProcessStepsLayout
in ProcessQueryStringController
in Unknown
in Unknown
in ProcessSearchFilterController
in Unknown
in Unknown
in ProcessController
in ProcessStepsLayoutLoader
in p
in DataBaseComponent
in Unknown
in KeyedItemAccessProvider
in ProcessStepsLayoutDataLoader
in WithProjectDeploymentProcess
in Unknown
in Page
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in Unknown
in RenderWithPage
in t
in t
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in BranchAwareRedirectInternal
in BranchAwareRedirect
in ProcessRoute
in withRouter(ProcessRoute)
in t
in t
in ErrorBoundaryInternal
in ReloadableRoute
in DeploymentsRoute
in withRouter(DeploymentsRoute)
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in ErrorBoundaryInternal
in RouteAwareErrorBoundary
in div
in div
in Unknown
in t
in Unknown
in MediaQuery
in div
in NavigationSidebarLayout
in withRouter(NavigationSidebarLayout)
in main
in ProjectContextProvider
in ProjectLayoutInternal
in p
in SlugSafeRedirect
in withRouter(SlugSafeRedirect)
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in ProjectRoutes
in n
in t
in ErrorBoundaryInternal
in ReloadableRoute
in t
in t
in RootRoutes
in withRouter(RootRoutes)
in SpaceLoader
in WithPersistedSpace
in p
in withRouter(Connect(WithPersistedSpace))
in div
in StandardLayoutInternal
in p
in t
in ErrorBoundaryInternal
in ReloadableRoute
in SecureRoute
in t
in Unknown
in Unknown
in t
in t
in Unknown
in DevToolsContextProvider
in ClientConnector
in W
in t
in Unknown
in h
in Unknown
in p
in DatabaseComponentContextProvider
in FieldErrorContextProvider
in ErrorContextProvider
in ErrorBoundaryInternal
in c
in App
```

### More Information

In previous versions (eg latest releases in streams 2021.1 and 2021.2), there was also no graceful validation message at all, but pressing the "Done" button would just do nothing. At least it was recoverable for the user.
