### ISSUE TITLE
Valid YAML can be considered invalid in Edit YAML popup on Deploy K8s container step, breaking page with react error

### ISSUE THREAD

**Issue by KennethBates** [OctopusDeploy/Issues#7363]
### Team

- [X] I've assigned a team label to this issue

### Severity

One report with a workaround

### Version

2021.3.11085

### What happened?

Valid YAML entered in the `Edit YAML` popup box on the `Deploy Kubernetes containers` step is *sometimes* considered invalid.

When YAML is considered invalid in this popup, this leads the user to hit #7260 which breaks the page with a react error. This was previously only known to occur on invalid YAML entry, but now found *some* valid YAML can cause this. Meaning valid YAML *can* break this page with a react error, requiring the user to refresh and start the step configuration all over again.

### Reproduction

1) Create a Deploy Kubernetes containers step
2) Click `Edit YAML`
3) Attempt to paste in the following example YAML

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Name
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExport
    spec:
      containers:
        - name: containerName
          image: Image
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
```

4) See error in UI

![image](https://user-images.githubusercontent.com/20388190/153113395-a65f2207-9b1c-4107-ad6c-c509aa6b3f6a.png)

### Error and Stacktrace

```shell
Browser console:


react-dom.production.min.js:209 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BFeedType%2C%20ApiVersion%2C%20RegistryPath%2C%20FeedUri%2C%20Username%2C%20Password%2C%20Name%2C%20PackageAcquisitionLocationOptions%2C%20SpaceId%2C%20Id%2C%20LastModifiedOn%2C%20LastModifiedBy%2C%20Links%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at _i (react-dom.production.min.js:139:47)
    at react-dom.production.min.js:149:278
    at Ia (react-dom.production.min.js:173:103)
    at wl (react-dom.production.min.js:265:156)
    at fs (react-dom.production.min.js:246:199)
    at ds (react-dom.production.min.js:246:128)
    at rs (react-dom.production.min.js:239:172)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)
    at Vo (react-dom.production.min.js:122:325)
```
```


### More Information

Reported here: https://octopus.zendesk.com/agent/tickets/83331 (private link)

### Workaround

Trial-and-error, but unfortunately when YAML is considered invalid it breaks the page with the react error requiring users to completely refresh and add the step from scratch.
