### ISSUE TITLE
Deploy K8 containers step incorrectly handles TcpSocket LivenessProbe config

### ISSUE THREAD

**Issue by pstephenson02** [OctopusDeploy/Issues#7414]
### Team

- [X] I've assigned a team label to this issue

### Severity

Low

### Version

2022.1

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using a liveness probe of type TcpSocket, upon saving the step settings, Octopus instead refers to the probe type as `httpGet`:

![image](https://user-images.githubusercontent.com/6306934/156848364-8441a331-7751-4ff0-b8ed-f6022a3a2cd0.png)
These settings in my container translate to this yaml:

```yml
    ...
    spec:
      containers:
        - name: redis
          image: index.docker.io/redis
          ports:
            - containerPort: 6379
          livenessProbe:
            httpGet:
              host: ''
              port: 6379
```

### Reproduction

Create a step using the Deploy Kubernetes containers built in step. Add a container and add a Liveness probe of type `TcpSocket`. Add the other required fields (container name, deployment name, etc.) and save the step. Then, view the raw YAML.

### Workaround

I could not come up with any workarounds because I'm also suffering from [this bug](https://github.com/OctopusDeploy/Issues/issues/7363)
