### ISSUE TITLE
YAML editor in Kubernetes step strips characters from variable whose name contain colons (`:`)

### ISSUE THREAD

**Issue by mjhilton** [OctopusDeploy/Issues#7428]
### Team

- [X] I've assigned a team label to this issue

### Severity

Blocking one customer

### Version

Present in 2021.3.12217, and perhaps earlier

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When using the `Deploy a Kubernetes Container` step, if you edit the YAML to enable variable replacement, and your variable name contains a colon `:` (for example, to support JSON-based Structured Configuration Variables in other parts of your app), the YAML editor strips everything after the first `:`.

### Reproduction

1. Create a project with a `Deploy Kubernetes Containers` step 
2. Click the `Edit YAML` button, and replace one of the fields (eg `spec / containers / image` with a variable in Variable Replacement syntax
```
spec:
  ...
  template:
    spec:
      containers:
      - name: my-pod
        image: 'index.docker.io/#{my:variable:name}'
...
```
3. Click Done on the YAML editor and save the step

**Expected**:
* YAML should save and roundtrip as it was entered. 
* Other parts of the Step should update with the entered values

**Actual**:
* Variable name is truncated after the first colon, in this example:
```
spec:
  ...
  template:
    spec:
      containers:
      - name: my-pod
        image: 'index.docker.io/#{my'
...
```
* Other parts of the Step that depend on the value of the YAML show truncated values
* Deployment doesn't resolve at runtime, and fails

### Error and Stacktrace
N/A

### More Information
[🎟️ Customer report](https://octopus.zendesk.com/agent/tickets/84825) (Internal)
[💬 Discussion thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1646663747590299) (Internal)

### Workaround
None currently known
