### ISSUE TITLE
AKS authentication using AzureAD Service Principal doesn't work when local accounts are disabled

### ISSUE THREAD

**Issue by cailyoung** [OctopusDeploy/Issues#7998]
### Team

- [X] I've assigned a team label to this issue

### Version

2023.1.6715

### Latest Version

I could reproduce the problem in the latest build

### What happened?

We use [AKS-managed AzureAD integration](https://learn.microsoft.com/en-us/azure/aks/managed-aad) in our AKS clusters. However, historically we have needed to use a service principal login requesting `--admin` credentials to deploy into the cluster from Octopus Deploy.

After [disabling local accounts](https://learn.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts) in a test AKS cluster, the deployment target starts to fail health checks and deployments fail, with an error like:

```
Operation failed with status: 'Bad Request'. Details: Getting static credential is not allowed because this cluster is set to disable local accounts. 
```

### Reproduction

[Internal Slack thread](https://octopusdeploy.slack.com/archives/C020P7U9Z9S/p1674078886765289)

* Have an AKS cluster with AzureAD integration for RBAC enabled
* Set it up as a deployment target using [Azure AD Service Principal](https://octopus.com/docs/infrastructure/deployment-targets/kubernetes-target) for auth
* [Disable local accounts](https://learn.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts) on the cluster
* Attempt to deploy using a Kubernetes step.

### Error and Stacktrace

```shell
Operation failed with status: 'Bad Request'. Details: Getting static credential is not allowed because this cluster is set to disable local accounts.
```

### More Information

The current supported method to enable the use of AzureAD accounts for control plane auth without 'local accounts' enabled  is to use `kubelogin` as a plugin. However, when trying this out myself by just adding it to a worker tools image, I found that the automatic setup of the `exec` step when running `az aks get-credentials` without `--admin` produced a kubeconfig containing this:

```yaml
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - 6dae42f8-4368-4678-94ff-3960e28e3630
      - --client-id
      - <redacted>
      - --tenant-id
      - <redacted>
      - --login
      - devicecode
      command: kubelogin
      env: null
      provideClusterInfo: false
```

That `devicecode` flag requires interaction on the first time it's run, so this is likely not as straightforward as dropping `kubelogin` into the deployment environment :(

https://github.com/Azure/kubelogin#spn-login-with-secret has an example of a kubeconfig set up for using a client secret directly. In running Terraform within Github Actions on other clusters with local accounts disabled, we found you can omit the `client-secret` from the config file and provide it as an environment variable `AAD_SERVICE_PRINCIPAL_CLIENT_SECRET` and that doesn't require interaction when run.

### Workaround

It's possible that switching to bearer-token authentication might work, but it'll require setting up a Kubernetes `ServiceAccount` and granting it the right permissions first, rather than using the AzureAD RBAC feature. I'm waiting to hear back from Microsoft as to whether that's supported.
