### ISSUE TITLE
Validation failure when using certificate data in Kubernetes Raw step

### ISSUE THREAD

**Issue by johnsimons** [OctopusDeploy/Issues#8322]
### Version

2023.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When you try to add a secret that contains certificate data, example
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
stringData:
  # the data is abbreviated in this example
  tls.crt: |
    --------BEGIN CERTIFICATE-----
    MIIC2DCCAcCgAwIBAgIBATANBgkqh ...    
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA7yn3bRHQ5FHMQ ...
```

The step fails to be saved, with the following error message:
![image](https://github.com/OctopusDeploy/Issues/assets/122651/786a454c-2cc4-45f5-aba2-145e9eeb7619)

### Reproduction

Try to create a raw yaml step using the above yaml.
