### ISSUE TITLE
Lack of multiline support in ADO v6 variables

### ISSUE THREAD

**Issue by veochen-octopus** [OctopusDeploy/Issues#8389]
### Version

ADO v6

### Latest Version

Not applicable

### What happened?

When trying to pass a multline value to a variable input in ADO v6, it takes only the first line regardless of the yaml syntax used (`|` or `>`). `\n` doesn't seem to be interpreted correctly. This is contrary to the [documentation](https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks) that says 
> List of prompted variable values, one variable-value pair per line. Each variable should be in format variable name: value

### Reproduction

Create a task with a yaml that looks like the following

```yaml
- task: OctopusRunRunbook@6
  name: <task name>
  inputs:
    OctoConnectedServiceName: "Octopus Server"
    Space: "Default"
    Project: "my-project"
    Runbook: "My Runbook"
    Environments: "Dev"
    Variables: |
      variable1: value1
      variable2: value2
```

This will only recognize `variable1`.
