### ISSUE TITLE
Kubenetes container deployment with custom yaml will not delete old custom resources

### ISSUE THREAD

**Issue by benPearce1** [OctopusDeploy/Issues#8589]
### Severity

Blocking some customers, but simple workaround available

### Version

2023.3

### Latest Version

I could reproduce the problem in the latest build

### What happened?

When deploying a _DEPLOY KUBERNETES CONTAINERS_ step with custom yaml that contains multiple resources, subsequent deployments will not remove the resources created by earlier deployments.
This issue is only observed when running on a *nix worker, the same problem does not occur when running on a Windows hosted worker.  

### Reproduction

With a _DEPLOY KUBERNETES CONTAINERS_ step, supply a custom yaml file with at least two resources on it.

Example:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    metrics-type: services
  name: '#{ServiceName}'
  namespace: '#{Namespace}'
spec:
  endpoints:
  - honorLabels: true
    interval: 60s
    path: /metrics
    scheme: http
    port: http
  namespaceSelector:
    matchNames:
    - '#{Namespace}'
  selector:
    matchLabels:
      Octopus.Kubernetes.DeploymentName: #{ServiceName}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '#{ServiceName}'
  namespace: '#{Namespace}'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: #{ServiceName}
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
```

When deploying this step, everything will work as expected the first time. Subsequent deployments will contian the follow message in the log, but no corresponding message for any other custom resources defined:
`servicemonitor.monitoring.coreos.com "service-2-deployments-82" deleted `

The cluster will also have these custom resources left behind.

### Workaround

Running the step on a Windows worker will not have the same issue and other resources in the custom yaml will be deleted.
